spring:
  profiles: dev
  datasource:
    master:
      url: jdbc:mysql://localhost:3306/benji?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
    slave1:
      url: jdbc:mysql://localhost:3306/benji?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
    slave2:
      url: jdbc:mysql://localhost:3306/benji?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.linkedcare.entity
  configuration:
    map-underscore-to-camel-case: true